(defun palindromep(input)
	(setq firstChar (first input))
	(setq lastChar (first(last input)))
	(cond 	
	  	( (equal nil input) (princ t) )
		( (= 1 (length input)) (princ t) )
		( (equal firstChar lastChar)
			(setq a2 (rest input))
			(setq internal (reverse (rest (reverse a2 ))))  
			(palindromep internal) ) 
		( (not(equal firstChar lastChar)) (princ nil) ) )
)

(defun main()
	(palindromep '(a b b a))
	(terpri)
	(palindromep '(a b c b a) )
	(terpri)
	(palindromep '(a b c) )
	(terpri)
	(palindromep '(a (d e) b (d e) a) )
	(terpri)
	(palindromep '(a (d e) b (e d) a) )
	(terpri)
)

(main)
